name: "S3CDN"
description: "Replicates basic unpkg.com functionality by uploading tagged releases to S3, with MAJOR, MINOR and PATCH version directories"
author: Foxy.io
branding:
  icon: repeat
  color: purple
inputs:
  package-name: # id of input
    description: "Package name"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.package-name }}
